name: near_camp
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.4.1
  firebase_dynamic_links: ^5.0.11
  uni_links: ^0.5.1

  cupertino_icons: ^1.0.5
  flutter_riverpod: ^2.1.3
  go_router: ^6.0.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  retrofit: ^3.3.1
  logger: ^1.1.0
  dio: ^4.0.6
  geolocator: ^9.0.2
  geocoding: ^2.0.5
  easy_localization: ^3.0.1
  extended_image: ^7.0.0
  kakao_flutter_sdk_share: ^1.4.0
  package_info_plus: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  freezed: ^2.3.2
  build_runner: ^2.3.3
  json_serializable: ^6.6.0
  retrofit_generator: ^4.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/images/geolocator/
    - assets/images/tour/
  fonts:
    - family: NanumSquareNeo
      fonts:
        - asset: assets/fonts/NanumSquareNeoOTF-aLt.otf
          weight: 300
        - asset: assets/fonts/NanumSquareNeoOTF-bRg.otf
          weight: 400
        - asset: assets/fonts/NanumSquareNeoOTF-cBd.otf
          weight: 700
        - asset: assets/fonts/NanumSquareNeoOTF-dEb.otf
          weight: 800
        - asset: assets/fonts/NanumSquareNeoOTF-eHv.otf
          weight: 900

  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
