// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'detail_info_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$_DetailInfoModel _$$_DetailInfoModelFromJson(Map<String, dynamic> json) =>
    _$_DetailInfoModel(
      roomimg5: json['roomimg5'] as String,
      roomimg5alt: json['roomimg5alt'] as String,
      contentid: json['contentid'] as String,
      contenttypeid: json['contenttypeid'] as String,
      fldgubun: json['fldgubun'] as String,
      infoname: json['infoname'] as String,
      infotext: json['infotext'] as String,
      serialnum: json['serialnum'] as String,
      subcontentid: json['subcontentid'] as String,
      subdetailalt: json['subdetailalt'] as String,
      subdetailimg: json['subdetailimg'] as String,
      subdetailoverview: json['subdetailoverview'] as String,
      subname: json['subname'] as String,
      subnum: json['subnum'] as String,
      roomcode: json['roomcode'] as String,
      roomtitle: json['roomtitle'] as String,
      roomsize1: json['roomsize1'] as String,
      roomcount: json['roomcount'] as String,
      roombasecount: json['roombasecount'] as String,
      roommaxcount: json['roommaxcount'] as String,
      roomoffseasonminfee1: json['roomoffseasonminfee1'] as String,
      roomoffseasonminfee2: json['roomoffseasonminfee2'] as String,
      roompeakseasonminfee1: json['roompeakseasonminfee1'] as String,
      roompeakseasonminfee2: json['roompeakseasonminfee2'] as String,
      roomintro: json['roomintro'] as String,
      roombathfacility: json['roombathfacility'] as String,
      roombath: json['roombath'] as String,
      roomhometheater: json['roomhometheater'] as String,
      roomaircondition: json['roomaircondition'] as String,
      roomtv: json['roomtv'] as String,
      roompc: json['roompc'] as String,
      roomcable: json['roomcable'] as String,
      roominternet: json['roominternet'] as String,
      roomrefrigerator: json['roomrefrigerator'] as String,
      roomtoiletries: json['roomtoiletries'] as String,
      roomsofa: json['roomsofa'] as String,
      roomcook: json['roomcook'] as String,
      roomtable: json['roomtable'] as String,
      roomhairdryer: json['roomhairdryer'] as String,
      roomsize2: json['roomsize2'] as String,
      roomimg1: json['roomimg1'] as String,
      roomimg1alt: json['roomimg1alt'] as String,
      roomimg2: json['roomimg2'] as String,
      roomimg2alt: json['roomimg2alt'] as String,
      roomimg3: json['roomimg3'] as String,
      roomimg4alt: json['roomimg4alt'] as String,
      roomimg3alt: json['roomimg3alt'] as String,
      roomimg: json['roomimg'] as String,
    );

Map<String, dynamic> _$$_DetailInfoModelToJson(_$_DetailInfoModel instance) =>
    <String, dynamic>{
      'roomimg5': instance.roomimg5,
      'roomimg5alt': instance.roomimg5alt,
      'contentid': instance.contentid,
      'contenttypeid': instance.contenttypeid,
      'fldgubun': instance.fldgubun,
      'infoname': instance.infoname,
      'infotext': instance.infotext,
      'serialnum': instance.serialnum,
      'subcontentid': instance.subcontentid,
      'subdetailalt': instance.subdetailalt,
      'subdetailimg': instance.subdetailimg,
      'subdetailoverview': instance.subdetailoverview,
      'subname': instance.subname,
      'subnum': instance.subnum,
      'roomcode': instance.roomcode,
      'roomtitle': instance.roomtitle,
      'roomsize1': instance.roomsize1,
      'roomcount': instance.roomcount,
      'roombasecount': instance.roombasecount,
      'roommaxcount': instance.roommaxcount,
      'roomoffseasonminfee1': instance.roomoffseasonminfee1,
      'roomoffseasonminfee2': instance.roomoffseasonminfee2,
      'roompeakseasonminfee1': instance.roompeakseasonminfee1,
      'roompeakseasonminfee2': instance.roompeakseasonminfee2,
      'roomintro': instance.roomintro,
      'roombathfacility': instance.roombathfacility,
      'roombath': instance.roombath,
      'roomhometheater': instance.roomhometheater,
      'roomaircondition': instance.roomaircondition,
      'roomtv': instance.roomtv,
      'roompc': instance.roompc,
      'roomcable': instance.roomcable,
      'roominternet': instance.roominternet,
      'roomrefrigerator': instance.roomrefrigerator,
      'roomtoiletries': instance.roomtoiletries,
      'roomsofa': instance.roomsofa,
      'roomcook': instance.roomcook,
      'roomtable': instance.roomtable,
      'roomhairdryer': instance.roomhairdryer,
      'roomsize2': instance.roomsize2,
      'roomimg1': instance.roomimg1,
      'roomimg1alt': instance.roomimg1alt,
      'roomimg2': instance.roomimg2,
      'roomimg2alt': instance.roomimg2alt,
      'roomimg3': instance.roomimg3,
      'roomimg4alt': instance.roomimg4alt,
      'roomimg3alt': instance.roomimg3alt,
      'roomimg': instance.roomimg,
    };
